version = 1
SPDX-PackageName = "KDUtils"
SPDX-PackageSupplier = "Paul Lemire <paul.lemire@kdab.com>"
SPDX-PackageDownloadLocation = "https://github.com/KDAB/KDUtils"

#misc source code
[[annotations]]
path = ["CMakePresets.json", "CMakeUserPresets-example.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "MIT"

#misc documentation
[[annotations]]
path = ["ChangeLog", "README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "MIT"

#misc config files
[[annotations]]
path = [".pre-commit-config.yaml", ".codespellrc", ".krazy", ".cmake-format.py", ".clang-format", ".clang-tidy", ".gitignore", ".gitreview", ".markdownlint.jsonc", "appveyor.yml", "REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "BSD-3-Clause"

#3rdparty
[[annotations]]
path = "cmake/CodeCoverage.cmake"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2012 - 2017, Lars Bilke"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["cmake/ECM/modules/**", "cmake/ECM/find-modules/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "The KDE Project"
SPDX-License-Identifier = "BSD-3-Clause"
